name: hotspot_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - anndata
  - argcomplete
  - argon2-cffi
  - attrs
  - backcall
  - bleach
  - cached-property
  - cffi
  - click
  - cycler
  - cython
  - decorator
  - defusedxml
  - docrep
  - dunamai
  - entrypoints
  - future
  - h5py
  - imageio
  - ipykernel
  - ipython
  - ipywidgets
  - jedi
  - jinja2
  - joblib
  - jsonschema
  - jupyterlab
  - kiwisolver
  - matplotlib
  - matplotlib-inline
  - mistune
  - natsort
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - networkx
  - notebook
  - numba
  - numexpr
  - numpy
  - packaging
  - pandas
  - pandocfilters
  - parso
  - patsy
  - pexpect
  - pickleshare
  - pillow
  - progressbar2
  - prompt-toolkit
  - pygam
  - pyparsing
  - pyrsistent
  - python-dateutil
  - python-igraph
  - pytz
  - pywavelets
  - pyzmq
  - scanpy
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - send2trash
  - setuptools
  - six
  - statsmodels
  - stdlib-list
  - tables=3.6.1  # add this line to the conda section

  - terminado
  - testpath
  - texttable
  - threadpoolctl
  - tifffile
  - tomli
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - umap-learn
  - wcwidth
  - webencodings
  - widgetsnbextension
  - wrapt
  - zipp
  - pip:
      - hotspotsc==0.9.1
      - get_version==3.5
      - POT==0.8.1.0
      - numpy-groupies==0.9.14
      - statot==0.0.14
      - venn==0.1.3
      - wot==1.0.8.post2
      - annoy==1.17.0
      - scvelo==0.2.4
      - jupyter-core==4.8.1
      - jupyter-client==7.0.3
      - jupyterlab-pygments==0.1.2
      - scrublet==0.2.3
      - sinfo==0.3.4
      - ipython-genutils==0.2.0
      - cellrank==1.5.1
      - importlib-resources==5.4.0
      - tables==3.6.1
      - debugpy==1.4.3
      - jupyterlab-widgets==1.0.2